spring.application.name=26-Student-Management

spring.datasource.url= jdbc:postgresql://localhost:5432/manage_app
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/WEB-INF/views/



#SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=srishtibhagat2003@gmail.com
spring.mail.password=nggj tvni mksn kqty
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.requires=true